=== Francisco-Aidenblue2/EjerciciosLMSGI/DTD/ExamenDTD/CatalogoDeProductosElectronicos.dtd
<!ELEMENT tienda (catalogo)>
<!ELEMENT catalogo (tipos*)>
<!ELEMENT tipos (CodigoIdentificador, nombre, descripcion, precio, puntuacion)>
<!ELEMENT nombre (#PCDATA | subnombre)*>
<!ELEMENT descipcion (opinion+)>
<!ELEMENT opinion (Positiva | Negativa)>
<!ELEMENT codigoIdentificador EMPTY>
<!ELEMENT opinion (#PCDATA)>
<!ELEMENT subnombre (#PCDATA)>
<!ELEMENT Positiva EMPTY>
<!ELEMENT Negativa EMPTY>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT puntuacion EMPTY>
<!ATTLIST tipos categoria CDATA #REQUIRED>

=== Francisco-Aidenblue2/EjerciciosLMSGI/DTD/ExamenDTD/CatalogoDeProductosElectronicos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tienda SYSTEM "CatalogoDeProductosElectronicos.dtd">

<tienda>
    <catalogo>
        <tipos categoria="grafica">
            <codigoIdentificador/>
            <nombre>RX 6650 XT
                <subnombre>6650 XT</subnombre>
            </nombre>
            <descripcion>
                <opinion>
                    <Positiva/>
                </opinion>
            </descripcion>
            <precio> 300€ </precio>
            <puntuacion/>

        </tipos>

        <tipos categoria="CPU">
            <codigoIdentificador/>
            <nombre>Ryzen 7600 </nombre>
            <descripcion> 
                <opinion>
                    <Negativa/>
                </opinion>
            </descripcion>
            <precio>280€ </precio>
            <puntuacion/>
        </tipos>


    </catalogo>
</tienda>
